export const FINANCIAL_TIPS = [
  "You don't need to match someone else's lifestyle to be considered successful.",
  "You deserve to treat yourself, but you also deserve the peace of mind of being debt-free.",
  "Stop buying things you don't need, to impress people who don't even care.",
  "Every peso you save is buying a piece of your future freedom.",
  "You're trading precious hours of your life for that salary. Is that purchase really worth your time?",
  "There is no shame in being frugal today if it means you won't be borrowing tomorrow.",
  "No matter how small, consistency wins. Pocket change eventually funds dreams.",
  "A little sacrifice today means you don't have to panic tomorrow.",
  "Don't let your temporary cravings empty your permanent savings.",
  "True wealth isn't about what you can buy; it's about sleeping soundly without the weight of debt.",
  "Money quickly vanishes when you say 'I deserve this' to everything. Be intentional with your cash.",
  "Your future self is begging you to be disciplined today.",
  "You can't heal a sad heart by swiping your credit card. Budget your emotions, too.",
  "Savings is not a punishment for your current self; it's a gift to your future self.",
  "Don't regret the money you put into savings; you are the only one who will harvest it.",
  "One day, you will stop working for money. Make sure your money starts working for you today.",
  "Don't look wealthy on social media but secretly struggle in real life.",
  "Your salary is a passing visitor. Make sure it leaves something behind before it goes.",
  "You don't need a massive income to start saving; you just need a massive amount of discipline.",
  "The best thing money can buy is peace of mind. Prioritize that.",
  "If you can't buy it in cash twice, you can't afford it once.",
  "Do not normalize taking out loans just to keep up with the latest trends.",
  "Richness is what people see. Wealth is the money you keep hidden and growing.",
  "The most expensive thing you can buy is a lifestyle you cannot maintain.",
  "It is okay to be cheap on things that don't matter, so you can be generous to your future.",
  "That daily expensive coffee adds up fast. Sometimes, the hole in your pocket is hidden in small habits.",
  "Stop waiting for a bigger salary to start saving. Start with what you currently have.",
  "Unnecessary debt is a chain you willingly wrap around yourself.",
  "Your financial stability will always be more attractive than a branded shirt.",
  "Respect your money, and your money will respect you back.",
  "Sleep on it before you check out your cart. If you don't want it tomorrow, you just saved yourself.",
  "It is not your responsibility to treat everyone on payday. Pay yourself first.",
  "If you want to help your family in the long run, you must build your own financial foundation first.",
  "Saving money isn't depriving yourself; it's loving the older version of yourself.",
  "Financial freedom starts the exact moment you stop caring about what others think of your budget.",
  "Don't wait until you're desperate to start saving. Save so you never become desperate.",
  "Every time you say 'no' to a random expense, you are saying 'yes' to your financial goals.",
  "Never borrow money to pay off borrowed money. Break the vicious cycle.",
  "There is no glory in showing off tonight if you have absolutely nothing tomorrow.",
  "True independence means not constantly waiting for the next payday just to survive.",
  "Don't let the fear of missing out (FOMO) ruin your bank account.",
  "A quiet, simple, debt-free life is highly underrated.",
  "Do not turn living paycheck-to-paycheck into an accepted lifestyle.",
  "You worked hard for that money. Why give it away so easily just because of a 'sale'?",
  "You do not need to justify your budget to anyone. It is your life, and your money.",
  "A dream will remain just a dream if you don't attach savings to it.",
  "Stop comparing your starting line to someone else's finish line. Focus entirely on your own savings.",
  "The goal isn't to look rich. The goal is to actually be financially free.",
  "Sometimes, the absolute best self-care is looking at your savings account and watching it grow.",
  "Do not succumb to peer pressure. You have different responsibilities than your friends.",
  "A real emergency is not a pair of shoes going on sale.",
  "Before you become generous to others, make sure you are generous to your emergency fund.",
  "Not every 'sale' saves you money. You only saved money if you actually needed the item.",
  "If you complain about your job every day, you should save harder so you have the freedom to quit.",
  "It's better to swallow your pride today and live simply, than swallow your pride tomorrow to ask for a loan.",
  "A moment of extreme patience in a store can save you a month of deep regret in your bank account.",
  "Pay yourself first. You earned that money, you have every right to keep some of it.",
  "You can save up for luxuries, but emergencies never give a warning. Always be prepared.",
  "Make saving a deeply ingrained habit, not just a random afterthought.",
  "It is never 'too late' to start saving. Even pocket change is still progress.",
  "Do not cure your work stress by spending. Cure it by saving so you can retire early.",
  "A solid bank account holds infinitely more comfort than a closet entirely full of clothes.",
  "Do not empty your salary trying to buy happiness. Peace of mind is greater than temporary joy.",
  "It is ultimately not about how much you make, but exactly how much you keep.",
  "Those who can endure a little hardship today will be blessed heavily tomorrow.",
  "Celebrate the success of others, but keep your eyes locked on your own financial journey.",
  "Do not upgrade your lifestyle every time your income increases. Upgrade your savings instead.",
  "No matter how high your salary is, without self-control, it will never be enough.",
  "Your financial future is created by what you do today, not what you plan to do tomorrow.",
  "Do not force a budget you do not have. Accept your reality today so you can change it tomorrow.",
  "If you cannot be content with what you have right now, you will never be content when you have more.",
  "Discipline weighs ounces, but financial regret weighs tons. Choose to save.",
  "Being broke is temporary, but a poor mindset is a lifetime sentence. Change how you view money.",
  "Stop treating your credit card like free money. It is a high-interest loan you must repay.",
  "Do not live by the 'You Only Live Once' motto if the ending is a mountain of debt.",
  "Save with the intention to invest, do not just save only to spend it later.",
  "It is absolutely fine to enjoy life, as long as you aren't using borrowed money to do it.",
  "Every single peso has a purpose. If you don't give it one, it will gladly leave you.",
  "Sometimes, the most romantic thing you can do for yourself is to build your savings.",
  "You survive 100% of your bad days. Ensure your finances are built to survive with you.",
  "Do not brag about your high salary if you have zero savings. Choose to be quietly wealthy.",
  "It takes years to build a savings net, and only a few minutes to ruin it with one bad decision.",
  "Refuse to let society dictate how you should spend your hard-earned money.",
  "Many people look wealthy but are drowning in debt. Choose the path of being debt-free.",
  "A delayed gratification always results in a much sweeter victory.",
  "Money is like a bar of soap; the more you handle it on useless things, the smaller it gets.",
  "Keep saving aggressively until your savings can pay for your lifestyle.",
  "Never compare your realistic journey to the heavily edited highlight reel of someone else.",
  "If a purchase does not bring you absolute peace of mind, it is not worth buying.",
  "Your absolute best investment will always be in yourself and your own financial literacy.",
  "A small amount of endurance today guarantees a large amount of comfort in the coming years.",
  "Focus all your energy on becoming wealthy, not just looking wealthy to strangers.",
  "Stop waiting for a sudden miracle to fix your finances. You have to be your own miracle.",
  "The money you are sacrificing to save today is the exact money that will save you when you are tired.",
  "Be fiercely proud of every single peso you manage to save. That is a real step towards your ultimate freedom.",
  "You do not need anyone's permission to start over and budget better this cut-off.",
  "Do not give up on saving. Just like working out, it hurts at first but the results are entirely worth it.",
  "The profound peace of mind provided by a fully funded emergency fund simply has no price tag.",
  "Be smart with money, because money has absolutely no emotions. You must be the one in control.",
  "At the end of the day, you only have yourself to rely on. Build your safety net immediately."
];
